spring.application.name=e-comm

# addding image folder 
project.image=images/

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000

spring.jpa.show-sql=true


spring.ecom.app.jwtCookieName=springBootEcom


# configuring databse
spring.datasource.url=jdbc:mysql://localhost:3306/ecomm
spring.datasource.username=root
spring.datasource.password=2004

spring.jpa.hibernate.ddl-auto=update